package com.yourcompany.incometracker.data.model

import androidx.room.Entity
import androidx.room.PrimaryKey

// Define the table name for Room
@Entity(tableName = "shipments")
data class Shipment(
    // Define the primary key, auto-generated by Room
    @PrimaryKey(autoGenerate = true) val id: Int = 0,

    // Name of the product shipped
    val productName: String,

    // Quantity of the product shipped
    val quantity: Int,

    // Destination where the product was sent
    val destination: String,

    // Date of the shipment (stored as milliseconds since epoch)
    val date: Long
) 